//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bas_attachment
    {
        public int Id { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Mode { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
        public string FileExt { get; set; }
        public Nullable<int> Length { get; set; }
        public string SourceCode { get; set; }
        public string SourceId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Layer { get; set; }
        public Nullable<int> IsDir { get; set; }
        public Nullable<int> IsTmpl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
