//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bas_notice_info
    {
        public int Id { get; set; }
        public string Sn { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string NoticeType { get; set; }
        public string NoticeSource { get; set; }
        public string Url { get; set; }
        public string SenderId { get; set; }
        public string SenderName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
