//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_msgboard_record
    {
        public int Id { get; set; }
        public Nullable<int> ReplyId { get; set; }
        public string GroupCode { get; set; }
        public string Author { get; set; }
        public string IdCard { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Ownership { get; set; }
        public string MsgTitle { get; set; }
        public string MsgContent { get; set; }
        public Nullable<int> IsAnonymous { get; set; }
        public Nullable<int> IsPublic { get; set; }
        public string Fields { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
