//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_publish_info
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public string Svn { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Creator { get; set; }
    }
}
