//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_address
    {
        public int Id { get; set; }
        public string UserAccount { get; set; }
        public string OrderCode { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Sex { get; set; }
        public string IdCardType { get; set; }
        public string IdCard { get; set; }
        public string Post { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public string Region { get; set; }
        public string Street { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
