//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_service_order
    {
        public int Id { get; set; }
        public string UserAccount { get; set; }
        public string OrderCode { get; set; }
        public string PayCode { get; set; }
        public string ServiceType { get; set; }
        public string Address { get; set; }
        public string Receiver { get; set; }
        public string Tel { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ReserveDate { get; set; }
        public Nullable<System.DateTime> SuccessDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
