//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_commodity_detail
    {
        public int Id { get; set; }
        public string FlightNo { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public string DeparturePlace { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string ArrivalPlace { get; set; }
        public string TakeOffTime { get; set; }
        public string LandingTime { get; set; }
        public string FlightTime { get; set; }
        public string Cabin { get; set; }
        public string Memo { get; set; }
        public int IsEnabled { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Creator { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<double> VipPrice { get; set; }
        public Nullable<double> ClubPrice { get; set; }
    }
}
