//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_order_item
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public string Type { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Model { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<int> OccupancyDay { get; set; }
        public string TakeOffTime { get; set; }
        public string LandingTime { get; set; }
        public string FlightTime { get; set; }
    }
}
