//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_member_corporation
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserAccount { get; set; }
        public string CorporationTel { get; set; }
        public string CorporationBreifName { get; set; }
        public string CorporationNature { get; set; }
        public string BusinessLicences { get; set; }
        public string CorporationName { get; set; }
        public string ApprovalDocument { get; set; }
        public string FireSafety { get; set; }
        public string InternetCulture { get; set; }
        public string BodyCorporateIdView { get; set; }
        public string BodyCorporateTel { get; set; }
        public string BodyCorporateIdCard { get; set; }
        public string BodyCorporate { get; set; }
        public string ChargeManIdView { get; set; }
        public string ChargeMan { get; set; }
        public string ChargeManTel { get; set; }
        public string ChargeManIdCard { get; set; }
        public string CorporationAddress { get; set; }
        public string longitude { get; set; }
        public string Altitudes { get; set; }
        public string BillboardView { get; set; }
        public string EnterView { get; set; }
        public string AllStaffForegroundView { get; set; }
        public string ChargForegroundView { get; set; }
        public string ForegroundView { get; set; }
        public string HallPanoramicView { get; set; }
        public string HallView { get; set; }
        public string CorporationIntro { get; set; }
        public string MemberLevel { get; set; }
    }
}
