//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_config
    {
        public int Id { get; set; }
        public string ConfigType { get; set; }
        public string ConfigName { get; set; }
        public string ConfigCode { get; set; }
        public string ConfigValue { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int IsEnabled { get; set; }
    }
}
