//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_action_detail
    {
        public int Id { get; set; }
        public int ActionId { get; set; }
        public string FieldCode { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Tag { get; set; }
    }
}
