//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPiculet.Base.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_member_data
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserAccount { get; set; }
        public string Nickname { get; set; }
        public string Birthday { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string MemberCard { get; set; }
        public string IdCard { get; set; }
        public string Education { get; set; }
        public string QQ { get; set; }
        public string Weixin { get; set; }
        public string Weibo { get; set; }
        public string Interest { get; set; }
        public Nullable<decimal> PointCurrent { get; set; }
        public Nullable<decimal> PointTotal { get; set; }
        public Nullable<decimal> Exp { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string HeadIcon { get; set; }
        public string Memo { get; set; }
        public string RechargeStatus { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
